### ISSUE TITLE
on every refresh new guest user is getting created

### ISSUE THREAD

**Issue by ajaygeorge91** [KyleU/play-silhouette-postgres-async-seed#1]
request.identity in "BaseController.withSession" is always None. For every request a new user gets created in the database.

**Comment by kyleu** [comment]
Whoops, right you are. I pulled this out of another project of mine, so it didn't get tested very well as a standalone app. I'll fix it up tonight!

**Comment by kyleu** [comment]
Actually, it looks like everything's working correctly. As long as cookies are enabled, you'll be tracked as a guest user until you register or sign in to a different account. Is this not what you're seeing?

**Comment by ajaygeorge91** [comment]
No. For me its not tracking the session. for every request separate userdata, anonymous session are getting created. I cannot track whats happening after eventbus.publish(...)
Cookies and all are enabled.

**Comment by kyleu** [comment]
What url do you use? It works for me when running on http://localhost:9000. What cookies do you see set? What is the value of s(ecuredRequest).identity in actions? Thanks again for looking in to this, I hope we can make it work for you!

**Comment by ajaygeorge91** [comment]
response
Set-Cookie:silhouette_auth=41f...afd12; Max-Age=31536000; Path=/; Domain=http://localhost:9000; HTTPOnly

---

app conf file

play {
  crypto.secret = "YSl...BkJ"
  play.i18n.langs = ["en"]

  session.cookieName = "silhouette_session"
  flash.cookieName = "silhouette_flash"
  akka.actor-system = "silhouette"
}

db {
  host = "localhost"
  database = "mydb"
  username = "postgres"
  password = "pass"
}

silhouette {
  authenticator {
    session {
      sessionKey = "auth"
      encryptAuthenticator = true
      useFingerprinting = false
      authenticatorIdleTimeout = 600
      authenticatorExpiry = 600
    }
    cookie {
      name = "silhouette_auth"
      path = "/"
      domain = "http://localhost:9000"
      secure = false
      useFingerprinting = false
      maxAge = 31536000 # One year in seconds
      #idleTimeout = 31536000 # One year in seconds
      expiry = 31536000 # One year in seconds
    }
  }

---

request.identity = None

**Comment by kyleu** [comment]
Hmm. I've run the app on a fresh OS X and Windows 8, and everything works as expected. Are you using the default routes and controller actions?

Play's request.identity is None normally (I'll fix that soon), but if you follow the withSession pattern, you deal with SecuredRequest, which has an identity field that isn't an Option[User], but is a direct User.

**Comment by kyleu** [comment]
Actually, now that I think about it, withSession doesn't even expose an Option[User] - what type is your request? Using withSession, it should be a SecuredRequest[User].

**Comment by ajaygeorge91** [comment]
the withSession in BaseController which takes (secureRequest => result)  is UserAwareAction.
I put a log in there (request.idendity) and its showing None. So every time when it passes through that request, its creating a new user.

I'm working on linux right now. Will try it in windows and give you the status. 
I'm pretty sure that this would be an error caused by misconfiguration or anything. This project is awesome by the way. Good work on the postgres async part. I could just start working directly on this after the fix. :)

**Comment by bbourget** [comment]
@ajaygeorge91 , your problem is with your cookie domain configuration.  

Just use a domain name in development and add it to your hosts file.

add this to your hosts file:
127.0.0.1   myweb.com

Update your cookie configuration:
    cookie {
      name = "silhouette_auth"
      path = "/"
      domain = "myweb.com"
      secure = false
      useFingerprinting = false
      maxAge = 31536000 # One year in seconds
      #idleTimeout = 31536000 # One year in seconds
      expiry = 31536000 # One year in seconds
    }

Then browse http://www.myweb.com:9000/ and all should be fine..

**Comment by ajaygeorge91** [comment]
I will check that. Thank you

Ajay George
