### ISSUE TITLE
Unexpected exception

### ISSUE THREAD

**Issue by jsdevelopcom** [KyleU/play-silhouette-postgres-async-seed#2]
Hi, I want to try your code in IntelliJ IDEA 15, using Import project from Version Control, run it and have:
GenericDatabaseException: ErrorMessage(fields=Map(Line -> 285, File -> auth.c, SQLSTATE -> 28P01, Routine -> auth_failed, Message -> password authentication failed for user "silhouette", Severity -> FATAL))  
No source available, here is the exception stack trace:
->com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Line -> 285, File -> auth.c, SQLSTATE -> 28P01, Routine -> auth_failed, Message -> password authentication failed for user "silhouette", Severity -> FATAL))
     com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:169)
     com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:151)
     io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
     io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
     io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
     io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
     io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
     io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
     io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
     io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
     io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
     io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
     io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
     io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
     io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
     java.lang.Thread.run(Thread.java:745)

**Comment by kyleu** [comment]
Create a postgres database named `silhouette`, owned by a new user `silhouette`, with the password `changeme`. Or, if you have an existing user/database, change `conf/application.conf` to point to your credentials.

**Comment by jsdevelopcom** [comment]
OK, THX, It works! )
